apiVersion: apps/v1
kind: Deployment
metadata:
  name: oskar-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oskar-api
  template:
    metadata:
      labels:
        app: oskar-api
    spec:
      containers:
        - name: oskar-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: oskar-config
          # Set heavy RAM requests because PyTorch + Whisper + Transformer models are loaded into memory
          resources:
            requests:
              memory: {{ .Values.api.resources.requests.memory | quote }}
              cpu: {{ .Values.api.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.api.resources.limits.memory | quote }}
              cpu: {{ .Values.api.resources.limits.cpu | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
      restartPolicy: Always
