# Default values for OSKAR Enterprise.

replicaCount: 1

image:
  repository: oskar-api
  pullPolicy: IfNotPresent
  tag: "latest"

# Environment Variables injected into API ConfigMap/Secrets
env:
  oskarApiKey: "oskar-dev-secret-key-123"
  adminKey: "oskar-admin-key-999"
  systemKey: "oskar-system-key-777"
  dbUrl: "postgresql://oskar_user:oskar_pass@oskar-postgres:5432/oskar_trust_db"
  redisHost: "oskar-redis"
  neo4jUri: "bolt://oskar-neo4j:7687"
  neo4jUser: "neo4j"
  neo4jPass: "oskarpass"

api:
  resources:
    limits:
      cpu: "4000m"
      memory: "8Gi"
    requests:
      cpu: "2000m"
      memory: "4Gi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75

neo4j:
  image: "neo4j:5.18.0"
  password: "oskarpass"
  persistence:
    size: 5Gi

postgres:
  image: "postgres:15-alpine"
  dbName: "oskar_trust_db"
  user: "oskar_user"
  password: "oskar_pass"
  persistence:
    size: 2Gi

redis:
  image: "redis:alpine"
